### ISSUE TITLE
NCAAM Stopped Working

### ISSUE THREAD

**Issue by jhealy2025** [vincep5/MMM-MyScoreboard#5]
Hi all,

Is anyone else not receiving scores and updates for NCAA men's basketball?

**Comment by jhealy2025** [comment]
I seem to have isolated the issue to this section of code:
/*
          by default, ESPN returns only the Top 25 ranked teams for NCAAF
          and NCAAM. By appending the group parameter (80 for NCAAF and 50
          for NCAAM, found in the URL of their respective scoreboard pages
          on ESPN.com) we'll get the entire game list.
    
          March Madness is grouped separately in ESPN's feed. The way I
          currently have things set up, I need to treat it like a different
          league.
        */
        if (league == "NCAAF") {
            url = url + "&groups=80";
        } else if (league == "NCAAM") {
            url = url + "&groups=50";
        } else if (league == "NCAAM_MM") {
            url = url + "&groups=100";
        }

The groups section seems to throw an error.  When the entire area is commented out the scores and schedule for the day shows up.  When the url is completed as: 

http://site.api.espn.com/apis/site/v2/sports/basketball/mens-college-basketball/scoreboard?dates=20181127&limit=200

it works.  When you add the grouping it returns an error.  Any thoughts?

http://site.api.espn.com/apis/site/v2/sports/basketball/mens-college-basketball/scoreboard?dates=20181127&limit=200&groups=50

**Comment by jhealy2025** [comment]
Also, as a side note, the logo for Iowa is not working under the NCAAM group.

**Comment by vincep5** [comment]
Mine is showing the NCAAM games for today fine.  Both the links work that you provided.

The Iowa logo from ESPN is all black, so on MM, it doesn't display nicely black on black background: http://a.espncdn.com/i/teamlogos/ncaa/500/2294.png  It's a down side of using ESPN, the original codebase uses local images and the local image is yellow.   I can look to see how to give it a different background, but there can be other teams that use black logos that would have to be adjusted, too.
